---
- name: glusterfs infra
  hosts: gluster_servers
  gather_facts: false

  vars_files:
    - vars/gluster_infra_vars.yml

  roles:
    - glusterfs.infra
    # - glusterfs.peers
    # - glusterfs.cluster-setup
    # - glusterfs.volume
